/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapturesRouteImport } from './routes/captures'
import { Route as FlowsFlowIdRouteImport } from './routes/flows/$flowId'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'
import { Route as RecreationsIndexRouteImport } from './routes/recreations/index'
import { Route as RecreationsRecreationIdRouteImport } from './routes/recreations/$recreationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesRoute = CapturesRouteImport.update({
  id: '/captures',
  path: '/captures',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdRoute = FlowsFlowIdRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecreationsIndexRoute = RecreationsIndexRouteImport.update({
  id: '/recreations/',
  path: '/recreations/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecreationsRecreationIdRoute = RecreationsRecreationIdRouteImport.update({
  id: '/recreations/$recreationId',
  path: '/recreations/$recreationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/captures': typeof CapturesRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/recreations/$recreationId': typeof RecreationsRecreationIdRoute
  '/recreations/': typeof RecreationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captures': typeof CapturesRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/recreations/$recreationId': typeof RecreationsRecreationIdRoute
  '/recreations': typeof RecreationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/captures': typeof CapturesRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/recreations/$recreationId': typeof RecreationsRecreationIdRoute
  '/recreations/': typeof RecreationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/captures'
    | '/flows/$flowId'
    | '/notes/$noteId'
    | '/recreations/$recreationId'
    | '/recreations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/captures'
    | '/flows/$flowId'
    | '/notes/$noteId'
    | '/recreations/$recreationId'
    | '/recreations'
  id:
    | '__root__'
    | '/'
    | '/captures'
    | '/flows/$flowId'
    | '/notes/$noteId'
    | '/recreations/$recreationId'
    | '/recreations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapturesRoute: typeof CapturesRoute
  FlowsFlowIdRoute: typeof FlowsFlowIdRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  RecreationsRecreationIdRoute: typeof RecreationsRecreationIdRoute
  RecreationsIndexRoute: typeof RecreationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures': {
      id: '/captures'
      path: '/captures'
      fullPath: '/captures'
      preLoaderRoute: typeof CapturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId': {
      id: '/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof FlowsFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recreations/': {
      id: '/recreations/'
      path: '/recreations'
      fullPath: '/recreations/'
      preLoaderRoute: typeof RecreationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recreations/$recreationId': {
      id: '/recreations/$recreationId'
      path: '/recreations/$recreationId'
      fullPath: '/recreations/$recreationId'
      preLoaderRoute: typeof RecreationsRecreationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapturesRoute: CapturesRoute,
  FlowsFlowIdRoute: FlowsFlowIdRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  RecreationsRecreationIdRoute: RecreationsRecreationIdRoute,
  RecreationsIndexRoute: RecreationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
